from common import *

ROOT_LOCATION = "/mnt/c/Users/anup9/Documents/Satisfactory"
REMOVELIST = [
    "Alien Carapace",
    "Alien Organs",
    "Bacon Agaric",
    "Beryl Nut",
    "Biomass",
    "Blade Runners",
    "Blue Power Slug",
    "Chainsaw",
    "Color Cartridge",
    "Fabric",
    "Factory Cart™",
    "FICSIT Coupon",
    "Flower Petals",
    "Gas Mask",
    "Gas Filter",
    "Golden Factory Cart™",
    "Hazmat Suit",
    "Hover Pack",
    "HUB Parts",
    "Iodine Infused Filter",
    "Jetpack",
    "Leaves",
    "Liquid Biofuel",
    "Medicinal Inhaler",
    "Mycelia",
    "Nobelisk Detonator",
    "Nobelisk",
    "Object Scanner",
    "Packaged Liquid Biofuel",
    "Paleberry",
    "Parachute",
    "Power Shard",
    "Purple Power Slug",
    "Portable Miner",
    "Rebar Gun",
    "Rifle Cartridge",
    "Rifle",
    "Xeno-Basher",
    "Xeno-Zapper",
    "Yellow Power Slug",
    "Zipline", 
    "Solid Biofuel", 
    "Spiked Rebar",
    "Wood",
    "Beacon"
    ]
RECIPE_PREFERENCES = {
    "Adaptive Control Unit": None,
    "AI Limiter": None,
    "Alclad Aluminum Sheet": None,
    "Alumina Solution": None,
    "Aluminum Casing": None,
    "Aluminum Ingot": None,
    "Aluminum Scrap": None,
    "Assembly Director System": None,
    "Automated Wiring": None,
    "Battery": None,
    "Bauxite": None,
    "Black Powder": None,
    "Cable": None,
    "Caterium Ingot": None,
    "Caterium Ore": None,
    "Circuit Board": None,
    "Coal": None,
    "Compacted Coal": None,
    "Computer": None,
    "Concrete": "Wet Concrete",
    "Cooling System": None,
    "Copper Ingot": None,
    "Copper Ore": None,
    "Copper Powder": None,
    "Copper Sheet": None,
    "Crude Oil": None,
    "Crystal Oscillator": None,
    "Electromagnetic Control Rod": None,
    "Empty Canister": None,
    "Empty Fluid Tank": None,
    "Encased Industrial Beam": None,
    "Encased Plutonium Cell": None,
    "Encased Uranium Cell": None,
    "Fuel": None,
    "Fused Modular Frame": None,
    "Heat Sink": None,
    "Heavy Modular Frame": None,
    "Heavy Oil Residue": None,
    "High-Speed Connector": None,
    "Iron Ingot": "Pure Iron Ingot",
    "Iron Ore": None,
    "Iron Plate": None,
    "Iron Rod": "Steel Rod",
    "Limestone": None,
    "Magnetic Field Generator": None,
    "Modular Engine": None,
    "Modular Frame": None,
    "Motor": None,
    "Nitric Acid": None,
    "Nitrogen Gas": None,
    "Non-fissile Uranium": None,
    "Nuclear Pasta": None,
    "Packaged Alumina Solution": None,
    "Packaged Fuel": None,
    "Packaged Heavy Oil Residue": None,
    "Packaged Nitric Acid": None,
    "Packaged Nitrogen Gas": None,
    "Packaged Oil": None,
    "Packaged Sulfuric Acid": None,
    "Packaged Turbofuel": None,
    "Packaged Water": None,
    "Petroleum Coke": None,
    "Plastic": None,
    "Plutonium Fuel Rod": None,
    "Plutonium Pellet": None,
    "Plutonium Waste": None,
    "Polymer Resin": None,
    "Pressure Conversion Cube": None,
    "Quartz Crystal": None,
    "Quickwire": None,
    "Radio Control Unit": None,
    "Raw Quartz": None,
    "Reinforced Iron Plate": None,
    "Rotor": None,
    "Rubber": None,
    "Screw": None,
    "Silica": None,
    "Smart Plating": None,
    "Stator": None,
    "Steel Beam": None,
    "Steel Ingot": None,
    "Steel Pipe": None,
    "Sulfur": None,
    "Sulfuric Acid": None,
    "Supercomputer": None,
    "Thermal Propulsion Rocket": None,
    "Turbo Motor": None,
    "Turbofuel": None,
    "Uranium Fuel Rod": None,
    "Uranium Waste": None,
    "Uranium": None,
    "Versatile Framework": None,
    "Water": None,
    "Wire": None
    }

def main():
    masterItems, masterRecipes = getItems()
    
    
if __name__ == "__main__":
    main()
